### ISSUE TITLE
nested folders not being demuddled

### ISSUE THREAD

**Issue by miedward** [Edru2/DeMuddler#8]
So for not very good reasons I have a nested structure in my scripts like
paulWalker (folder)
    -> paulWalker (no folder icon but has child script object)
          -> walker (actual script here)
demudler doesn't see the (grand?) child script in this situation.

The package exporter handles it fine, so this appears to be a valid mudlet object so possibly of interest to handle.
I'm probably just going to remove the extra level of nesting so this is mostly to document the unhandled corner case.

**Comment by Edru2** [comment]
:thinking: So the second paulWalker is not a Folder but a script with a child script?

**Comment by miedward** [comment]
Yeah, I'm not sure it's worth dealing with but apparently at least scripts can have children even if they're not folders.  Possibly only if you like, import from XML or something odd.  ¯\_(ツ)_/¯

**Comment by mpconley** [comment]
Yes, I had this happen as well where some code was not created for child scripts of scripts. This was something that demmonic had [in his video](https://www.youtube.com/watch?v=LNKl0BZud5c) as well so it will be great when it is supported here too.
<img width="1150" alt="Screenshot 2024-06-30 at 12 00 41 PM" src="https://github.com/Edru2/DeMuddler/assets/3058178/d49322b0-d89d-4eb6-865d-a8647d612efc">

**Comment by Edru2** [comment]
ok. 
The issue was that I assumed children were only possible for Triggers because I didn't see any children field in https://github.com/demonnic/muddler/wiki/Scripts but there was one in https://github.com/demonnic/muddler/wiki/Triggers#triggersjson so for triggers they should already work.
Now after testing it I noticed that muddler can also handle them for scripts (and probably also for keys, timers...).
Will look into adding it to de-muddler as well :sweat_smile:

**Comment by Edru2** [comment]
should be fixed in the latest release
